networks:
  web:
    external: true  

services:
  vixsrc-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vixsrc-extractor
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    networks:
      - web
    mem_limit: 512m
    cpus: 1.0
    ports:
      - "5000:5000"