services:
  vixsrc-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vixsrc-extractor-docker
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    expose:
      - "5000" # vedere discordo rete nginx
